name: Frontend Pull Request

on:
  pull_request:
    branches: 
      - main
      
jobs:
  build-and-push-test:
    runs-on: ubuntu-latest  
    environment: production

    steps:
    - 
      name: Checkout Repository
      uses: actions/checkout@v4  
      # 현재 리포지토리를 체크아웃합니다.

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  
      # Docker Buildx를 설정합니다.

    - 
      name: Build and Push
      uses: docker/build-push-action@v6
      with:
        # 빌드 컨텍스트 : Dockerfile이 있는 위치
        context: .
        # Dockerfile의 경로
        file: Dockerfile
        build-args: |
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            BACKEND_HOST=${{ secrets.BACKEND_HOST }}
            BACKEND_PORT=${{ secrets.BACKEND_PORT }}
        push: false  # 이미지를 레지스트리에 푸시여부.
        cache-from: type=gha  # GitHub Actions 캐시 사용
        cache-to: type=gha,mode=max  # 빌드 캐시 저장
